# Cloud Deploy delivery pipeline configuration
# Defines the promotion pipeline: dev → staging → prod

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: order-api-pipeline
spec:
  description: "Order API delivery pipeline for dev, staging, and production"
  serialPipeline:
    stages:
      # Stage 1: Development environment
      - targetId: order-api-dev
        profiles: ['dev']
        strategy:
          standard:
            verify: true

      # Stage 2: Staging environment
      - targetId: order-api-staging
        profiles: ['staging']
        strategy:
          standard:
            verify: true

      # Stage 3: Production environment (requires approval)
      - targetId: order-api-prod
        profiles: ['prod']
        strategy:
          standard:
            verify: true
            requireApproval: true

---
# Cloud Run target for Development environment
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: order-api-dev
spec:
  description: "Development environment for Order API"
  run:
    location: projects/${PROJECT_ID}/locations/asia-south1

---
# Cloud Run target for Staging environment
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: order-api-staging
spec:
  description: "Staging environment for Order API"
  run:
    location: projects/${PROJECT_ID}/locations/asia-south1

---
# Cloud Run target for Production environment
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: order-api-prod
spec:
  description: "Production environment for Order API"
  run:
    location: projects/${PROJECT_ID}/locations/asia-south1

